/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
/**
 *
 * @author Alicia Sandoval
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form frmTraductor
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JLabel();
        txtTexto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTraducir = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 153));

        txtTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        txtTitle.setText("Traductor Español-Código Braille");

        txtTexto.setFont(new java.awt.Font("Comic Sans MS", 0, 30)); // NOI18N
        txtTexto.setText("Texto a traducir:");

        txtTraducir.setColumns(20);
        txtTraducir.setFont(new java.awt.Font("Monospaced", 0, 36)); // NOI18N
        txtTraducir.setRows(5);
        jScrollPane1.setViewportView(txtTraducir);

        btnLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnLimpiar.setText("Limpiar pantalla");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnAceptar.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptar.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 255, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTexto)
                                .addGap(26, 26, 26)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitle)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(txtTexto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static void escribir(String ar){
        File miDir=new File(".");
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            fichero = new FileWriter("traductor.html", false);
            fichero.write(ar);
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                //Nuevamente aprobechamos el finally para
                //asegurarnos que se cierra el fichero
                if (null != fichero) {
                    fichero.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    static String linea;
    static String archivoAt="";
    public static String leer() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        File miDir=new File(".");
        String lin = "";
        try {
            //Apertura del fichero y creacion de BufferedReader para poder
            //hacer una lectura comoda(disponer del metodo readLine()).
            archivo = new File(miDir.getCanonicalPath()+"\\traductor.html");
            archivoAt=""+miDir.getCanonicalPath()+"\\traductor.html";
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            
            //lectura del fichero
//            while ((linea = br.readLine()) != null) {
                lin = linea;
//            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            //en el finally cerramos el fichero, para asegurarnos
            //que se cierra tanto si todo va bien como si salta
            //una excepcion
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        return lin;
    }
    public String generaHTML(String[] imagenes){
            String txtHtml="";
            txtHtml += "<!DOCTYPE HTML>";
            txtHtml += "<html>";
            txtHtml += "	<head>";
            txtHtml += "	<meta charset=utf-8>";
            txtHtml += "		<title>Traductor español-braille</title>";
           /* txtHtml += "		<script src=\"js/jquery.min.js\"></script>";
            txtHtml += "		<script src=\"js/jquery.scrolly.min.js\"></script>";
            txtHtml += "		<script src=\"js/skel.min.js\"></script>";
            txtHtml += "		<script src=\"js/init.js\"></script>";
            txtHtml += "		<noscript>";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/skel.css\" />";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/style.css\" />";
            txtHtml += "			<link rel=\"stylesheet\" href=\"css/style-desktop.css\" />";
            txtHtml += "		</noscript>";
            txtHtml += "		<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"css/ie/v8.css\" /><![endif]-->";
            txtHtml += "		<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"css/ie/v9.css\" /><![endif]-->";*/
            txtHtml += "	</head>";
            txtHtml += "	<body BGCOLOR=\"pink\">";
            txtHtml += "";
            txtHtml += "		<!-- Nav -->";
            txtHtml += "			<nav id=\"nav\">";
            txtHtml += "				<ul class=\"container\">";
            txtHtml += "					<center><H1><font FACE=\"Comic Sans MS\" SIZE=10 COLOR=blue>Traductor español - código braille</a></H1></center></font>";
            txtHtml += "					<center><H3><font FACE=\"Comic Sans MS\" SIZE=4 COLOR=black>Alicia Sandoval Camacho</a></H3></center></font>";
            txtHtml += "				</ul>";
            txtHtml += "			</nav>";
            txtHtml += "";
            txtHtml += "		<!-- Work -->";
            txtHtml += "				";
            txtHtml += "		<!-- Contact -->";
            txtHtml += "			<div class=\"wrapper style4\">";
            txtHtml += "				<article id=\"contact\" class=\"container 75%\">";
            for (int i=0;i<imagenes.length;i++) {
                if(imagenes[i]!=null && imagenes[i]!="")
                txtHtml+="<img src=\"src\\javaapplication21\\imagenes\\"+imagenes[i]+"\" width=80 height=100>";
            }
            txtHtml += "				</article>";
            txtHtml += "			</div>";
            txtHtml += "";
            txtHtml += "	</body>";
            txtHtml += "</html>";

        return txtHtml;
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

            txtTraducir.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String txtTraduccion=txtTraducir.getText();
        if(txtTraduccion.equals(null) || txtTraduccion.equals("")){
           JOptionPane.showMessageDialog(null,"Sin entrada");
            return;
        }
        txtTraduccion=txtTraduccion.toLowerCase();
        txtTraduccion=txtTraduccion.replaceAll("\n", " ");
        char letra[]=new char[10000];
                letra= txtTraduccion.toCharArray();
        Traductor t=new Traductor(letra);
        String[] imagenes =new String[10000];
                imagenes= t.getTraduccion();
        
        escribir(generaHTML(imagenes));
        JOptionPane.showMessageDialog(null,"Traducción completa");
        JOptionPane.showMessageDialog(null,"HTML creado");
        try {
            Runtime.getRuntime().exec("cmd /c start traductor.html");
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtTexto;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JTextArea txtTraducir;
    // End of variables declaration//GEN-END:variables
}
